// Cities by US State - Major cities for each state
export const citiesByState: Record<string, { value: string; label: string }[]> = {
    AL: [ // Alabama
        { value: "birmingham", label: "Birmingham" },
        { value: "montgomery", label: "Montgomery" },
        { value: "huntsville", label: "Huntsville" },
        { value: "mobile", label: "Mobile" },
        { value: "tuscaloosa", label: "Tuscaloosa" },
    ],
    AK: [ // Alaska
        { value: "anchorage", label: "Anchorage" },
        { value: "fairbanks", label: "Fairbanks" },
        { value: "juneau", label: "Juneau" },
        { value: "sitka", label: "Sitka" },
        { value: "ketchikan", label: "Ketchikan" },
    ],
    AZ: [ // Arizona
        { value: "phoenix", label: "Phoenix" },
        { value: "tucson", label: "Tucson" },
        { value: "mesa", label: "Mesa" },
        { value: "chandler", label: "Chandler" },
        { value: "scottsdale", label: "Scottsdale" },
        { value: "glendale", label: "Glendale" },
        { value: "tempe", label: "Tempe" },
    ],
    AR: [ // Arkansas
        { value: "little_rock", label: "Little Rock" },
        { value: "fayetteville", label: "Fayetteville" },
        { value: "fort_smith", label: "Fort Smith" },
        { value: "springdale", label: "Springdale" },
        { value: "jonesboro", label: "Jonesboro" },
    ],
    CA: [ // California
        { value: "los_angeles", label: "Los Angeles" },
        { value: "san_francisco", label: "San Francisco" },
        { value: "san_diego", label: "San Diego" },
        { value: "sacramento", label: "Sacramento" },
        { value: "san_jose", label: "San Jose" },
        { value: "fresno", label: "Fresno" },
        { value: "long_beach", label: "Long Beach" },
        { value: "oakland", label: "Oakland" },
        { value: "bakersfield", label: "Bakersfield" },
        { value: "anaheim", label: "Anaheim" },
    ],
    CO: [ // Colorado
        { value: "denver", label: "Denver" },
        { value: "colorado_springs", label: "Colorado Springs" },
        { value: "aurora", label: "Aurora" },
        { value: "fort_collins", label: "Fort Collins" },
        { value: "lakewood", label: "Lakewood" },
        { value: "boulder", label: "Boulder" },
    ],
    CT: [ // Connecticut
        { value: "bridgeport", label: "Bridgeport" },
        { value: "new_haven", label: "New Haven" },
        { value: "hartford", label: "Hartford" },
        { value: "stamford", label: "Stamford" },
        { value: "waterbury", label: "Waterbury" },
    ],
    DE: [ // Delaware
        { value: "wilmington", label: "Wilmington" },
        { value: "dover", label: "Dover" },
        { value: "newark", label: "Newark" },
        { value: "bear", label: "Bear" },
    ],
    FL: [ // Florida
        { value: "jacksonville", label: "Jacksonville" },
        { value: "miami", label: "Miami" },
        { value: "tampa", label: "Tampa" },
        { value: "orlando", label: "Orlando" },
        { value: "st_petersburg", label: "St. Petersburg" },
        { value: "hialeah", label: "Hialeah" },
        { value: "tallahassee", label: "Tallahassee" },
        { value: "fort_lauderdale", label: "Fort Lauderdale" },
        { value: "port_st_lucie", label: "Port St. Lucie" },
    ],
    GA: [ // Georgia
        { value: "atlanta", label: "Atlanta" },
        { value: "columbus", label: "Columbus" },
        { value: "augusta", label: "Augusta" },
        { value: "savannah", label: "Savannah" },
        { value: "athens", label: "Athens" },
        { value: "sandy_springs", label: "Sandy Springs" },
    ],
    HI: [ // Hawaii
        { value: "honolulu", label: "Honolulu" },
        { value: "hilo", label: "Hilo" },
        { value: "kailua_kona", label: "Kailua-Kona" },
        { value: "kahului", label: "Kahului" },
    ],
    ID: [ // Idaho
        { value: "boise", label: "Boise" },
        { value: "nampa", label: "Nampa" },
        { value: "meridian", label: "Meridian" },
        { value: "idaho_falls", label: "Idaho Falls" },
        { value: "pocatello", label: "Pocatello" },
    ],
    IL: [ // Illinois
        { value: "chicago", label: "Chicago" },
        { value: "aurora", label: "Aurora" },
        { value: "rockford", label: "Rockford" },
        { value: "joliet", label: "Joliet" },
        { value: "naperville", label: "Naperville" },
        { value: "springfield", label: "Springfield" },
        { value: "peoria", label: "Peoria" },
    ],
    IN: [ // Indiana
        { value: "indianapolis", label: "Indianapolis" },
        { value: "fort_wayne", label: "Fort Wayne" },
        { value: "evansville", label: "Evansville" },
        { value: "south_bend", label: "South Bend" },
        { value: "carmel", label: "Carmel" },
    ],
    IA: [ // Iowa
        { value: "des_moines", label: "Des Moines" },
        { value: "cedar_rapids", label: "Cedar Rapids" },
        { value: "davenport", label: "Davenport" },
        { value: "sioux_city", label: "Sioux City" },
        { value: "iowa_city", label: "Iowa City" },
    ],
    KS: [ // Kansas
        { value: "wichita", label: "Wichita" },
        { value: "overland_park", label: "Overland Park" },
        { value: "kansas_city", label: "Kansas City" },
        { value: "topeka", label: "Topeka" },
        { value: "olathe", label: "Olathe" },
    ],
    KY: [ // Kentucky
        { value: "louisville", label: "Louisville" },
        { value: "lexington", label: "Lexington" },
        { value: "bowling_green", label: "Bowling Green" },
        { value: "owensboro", label: "Owensboro" },
        { value: "covington", label: "Covington" },
    ],
    LA: [ // Louisiana
        { value: "new_orleans", label: "New Orleans" },
        { value: "baton_rouge", label: "Baton Rouge" },
        { value: "shreveport", label: "Shreveport" },
        { value: "lafayette", label: "Lafayette" },
        { value: "lake_charles", label: "Lake Charles" },
    ],
    ME: [ // Maine
        { value: "portland", label: "Portland" },
        { value: "lewiston", label: "Lewiston" },
        { value: "bangor", label: "Bangor" },
        { value: "south_portland", label: "South Portland" },
        { value: "augusta", label: "Augusta" },
    ],
    MD: [ // Maryland
        { value: "baltimore", label: "Baltimore" },
        { value: "frederick", label: "Frederick" },
        { value: "rockville", label: "Rockville" },
        { value: "gaithersburg", label: "Gaithersburg" },
        { value: "bowie", label: "Bowie" },
        { value: "annapolis", label: "Annapolis" },
    ],
    MA: [ // Massachusetts
        { value: "boston", label: "Boston" },
        { value: "worcester", label: "Worcester" },
        { value: "springfield", label: "Springfield" },
        { value: "lowell", label: "Lowell" },
        { value: "cambridge", label: "Cambridge" },
        { value: "new_bedford", label: "New Bedford" },
    ],
    MI: [ // Michigan
        { value: "detroit", label: "Detroit" },
        { value: "grand_rapids", label: "Grand Rapids" },
        { value: "warren", label: "Warren" },
        { value: "sterling_heights", label: "Sterling Heights" },
        { value: "lansing", label: "Lansing" },
        { value: "ann_arbor", label: "Ann Arbor" },
    ],
    MN: [ // Minnesota
        { value: "minneapolis", label: "Minneapolis" },
        { value: "saint_paul", label: "Saint Paul" },
        { value: "rochester", label: "Rochester" },
        { value: "duluth", label: "Duluth" },
        { value: "bloomington", label: "Bloomington" },
    ],
    MS: [ // Mississippi
        { value: "jackson", label: "Jackson" },
        { value: "gulfport", label: "Gulfport" },
        { value: "southaven", label: "Southaven" },
        { value: "hattiesburg", label: "Hattiesburg" },
        { value: "biloxi", label: "Biloxi" },
    ],
    MO: [ // Missouri
        { value: "kansas_city", label: "Kansas City" },
        { value: "saint_louis", label: "Saint Louis" },
        { value: "springfield", label: "Springfield" },
        { value: "columbia", label: "Columbia" },
        { value: "independence", label: "Independence" },
    ],
    MT: [ // Montana
        { value: "billings", label: "Billings" },
        { value: "missoula", label: "Missoula" },
        { value: "great_falls", label: "Great Falls" },
        { value: "bozeman", label: "Bozeman" },
        { value: "helena", label: "Helena" },
    ],
    NE: [ // Nebraska
        { value: "omaha", label: "Omaha" },
        { value: "lincoln", label: "Lincoln" },
        { value: "bellevue", label: "Bellevue" },
        { value: "grand_island", label: "Grand Island" },
        { value: "kearney", label: "Kearney" },
    ],
    NV: [ // Nevada
        { value: "las_vegas", label: "Las Vegas" },
        { value: "henderson", label: "Henderson" },
        { value: "reno", label: "Reno" },
        { value: "north_las_vegas", label: "North Las Vegas" },
        { value: "sparks", label: "Sparks" },
        { value: "carson_city", label: "Carson City" },
    ],
    NH: [ // New Hampshire
        { value: "manchester", label: "Manchester" },
        { value: "nashua", label: "Nashua" },
        { value: "concord", label: "Concord" },
        { value: "derry", label: "Derry" },
        { value: "rochester", label: "Rochester" },
    ],
    NJ: [ // New Jersey
        { value: "newark", label: "Newark" },
        { value: "jersey_city", label: "Jersey City" },
        { value: "paterson", label: "Paterson" },
        { value: "elizabeth", label: "Elizabeth" },
        { value: "edison", label: "Edison" },
        { value: "trenton", label: "Trenton" },
    ],
    NM: [ // New Mexico
        { value: "albuquerque", label: "Albuquerque" },
        { value: "las_cruces", label: "Las Cruces" },
        { value: "rio_rancho", label: "Rio Rancho" },
        { value: "santa_fe", label: "Santa Fe" },
        { value: "roswell", label: "Roswell" },
    ],
    NY: [ // New York
        { value: "new_york_city", label: "New York City" },
        { value: "buffalo", label: "Buffalo" },
        { value: "rochester", label: "Rochester" },
        { value: "yonkers", label: "Yonkers" },
        { value: "syracuse", label: "Syracuse" },
        { value: "albany", label: "Albany" },
        { value: "new_rochelle", label: "New Rochelle" },
    ],
    NC: [ // North Carolina
        { value: "charlotte", label: "Charlotte" },
        { value: "raleigh", label: "Raleigh" },
        { value: "greensboro", label: "Greensboro" },
        { value: "durham", label: "Durham" },
        { value: "winston_salem", label: "Winston-Salem" },
        { value: "fayetteville", label: "Fayetteville" },
    ],
    ND: [ // North Dakota
        { value: "fargo", label: "Fargo" },
        { value: "bismarck", label: "Bismarck" },
        { value: "grand_forks", label: "Grand Forks" },
        { value: "minot", label: "Minot" },
        { value: "west_fargo", label: "West Fargo" },
    ],
    OH: [ // Ohio
        { value: "columbus", label: "Columbus" },
        { value: "cleveland", label: "Cleveland" },
        { value: "cincinnati", label: "Cincinnati" },
        { value: "toledo", label: "Toledo" },
        { value: "akron", label: "Akron" },
        { value: "dayton", label: "Dayton" },
    ],
    OK: [ // Oklahoma
        { value: "oklahoma_city", label: "Oklahoma City" },
        { value: "tulsa", label: "Tulsa" },
        { value: "norman", label: "Norman" },
        { value: "broken_arrow", label: "Broken Arrow" },
        { value: "lawton", label: "Lawton" },
    ],
    OR: [ // Oregon
        { value: "portland", label: "Portland" },
        { value: "salem", label: "Salem" },
        { value: "eugene", label: "Eugene" },
        { value: "gresham", label: "Gresham" },
        { value: "hillsboro", label: "Hillsboro" },
        { value: "bend", label: "Bend" },
    ],
    PA: [ // Pennsylvania
        { value: "philadelphia", label: "Philadelphia" },
        { value: "pittsburgh", label: "Pittsburgh" },
        { value: "allentown", label: "Allentown" },
        { value: "erie", label: "Erie" },
        { value: "reading", label: "Reading" },
        { value: "scranton", label: "Scranton" },
        { value: "harrisburg", label: "Harrisburg" },
    ],
    RI: [ // Rhode Island
        { value: "providence", label: "Providence" },
        { value: "cranston", label: "Cranston" },
        { value: "warwick", label: "Warwick" },
        { value: "pawtucket", label: "Pawtucket" },
        { value: "east_providence", label: "East Providence" },
    ],
    SC: [ // South Carolina
        { value: "charleston", label: "Charleston" },
        { value: "columbia", label: "Columbia" },
        { value: "north_charleston", label: "North Charleston" },
        { value: "mount_pleasant", label: "Mount Pleasant" },
        { value: "rock_hill", label: "Rock Hill" },
    ],
    SD: [ // South Dakota
        { value: "sioux_falls", label: "Sioux Falls" },
        { value: "rapid_city", label: "Rapid City" },
        { value: "aberdeen", label: "Aberdeen" },
        { value: "brookings", label: "Brookings" },
        { value: "pierre", label: "Pierre" },
    ],
    TN: [ // Tennessee
        { value: "nashville", label: "Nashville" },
        { value: "memphis", label: "Memphis" },
        { value: "knoxville", label: "Knoxville" },
        { value: "chattanooga", label: "Chattanooga" },
        { value: "clarksville", label: "Clarksville" },
    ],
    TX: [ // Texas
        { value: "houston", label: "Houston" },
        { value: "san_antonio", label: "San Antonio" },
        { value: "dallas", label: "Dallas" },
        { value: "austin", label: "Austin" },
        { value: "fort_worth", label: "Fort Worth" },
        { value: "el_paso", label: "El Paso" },
        { value: "arlington", label: "Arlington" },
        { value: "corpus_christi", label: "Corpus Christi" },
        { value: "plano", label: "Plano" },
        { value: "lubbock", label: "Lubbock" },
    ],
    UT: [ // Utah
        { value: "salt_lake_city", label: "Salt Lake City" },
        { value: "west_valley_city", label: "West Valley City" },
        { value: "provo", label: "Provo" },
        { value: "west_jordan", label: "West Jordan" },
        { value: "orem", label: "Orem" },
    ],
    VT: [ // Vermont
        { value: "burlington", label: "Burlington" },
        { value: "essex", label: "Essex" },
        { value: "south_burlington", label: "South Burlington" },
        { value: "colchester", label: "Colchester" },
        { value: "montpelier", label: "Montpelier" },
    ],
    VA: [ // Virginia
        { value: "virginia_beach", label: "Virginia Beach" },
        { value: "norfolk", label: "Norfolk" },
        { value: "chesapeake", label: "Chesapeake" },
        { value: "richmond", label: "Richmond" },
        { value: "newport_news", label: "Newport News" },
        { value: "alexandria", label: "Alexandria" },
    ],
    WA: [ // Washington
        { value: "seattle", label: "Seattle" },
        { value: "spokane", label: "Spokane" },
        { value: "tacoma", label: "Tacoma" },
        { value: "vancouver", label: "Vancouver" },
        { value: "bellevue", label: "Bellevue" },
        { value: "everett", label: "Everett" },
    ],
    WV: [ // West Virginia
        { value: "charleston", label: "Charleston" },
        { value: "huntington", label: "Huntington" },
        { value: "parkersburg", label: "Parkersburg" },
        { value: "morgantown", label: "Morgantown" },
        { value: "wheeling", label: "Wheeling" },
    ],
    WI: [ // Wisconsin
        { value: "milwaukee", label: "Milwaukee" },
        { value: "madison", label: "Madison" },
        { value: "green_bay", label: "Green Bay" },
        { value: "kenosha", label: "Kenosha" },
        { value: "racine", label: "Racine" },
    ],
    WY: [ // Wyoming
        { value: "cheyenne", label: "Cheyenne" },
        { value: "casper", label: "Casper" },
        { value: "laramie", label: "Laramie" },
        { value: "gillette", label: "Gillette" },
        { value: "rock_springs", label: "Rock Springs" },
    ],
};

// Function to get cities by state
export const getCitiesByState = (stateCode: string): { value: string; label: string }[] => {
    return citiesByState[stateCode] || [];
};